version: 2
jobs:
  build:  # required for runs that don't use workflows
    machine: true
    working_directory: ~/Git/sa-uta7-recall-precision
    steps:
      - checkout
      - run: sudo python -m pip install --upgrade pip
      - run: sudo pip install -r requirements.txt