version: 2
jobs:
  build:  # required for runs that don't use workflows
    machine: true
    working_directory: ~/Git/sa-uta7-recall-precision
    steps:
      - checkout  # checkout source code to working directory
      - run:
        name: "Do things!"
        command: python3 src/core/main.py